# Generated by Django 3.2.15 on 2024-02-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0072_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='<function uuid4 at 0x10173d2d0>', max_length=150),
        ),
        migrations.AlterField(
            model_name='trackfile',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='music_room.track'),
        ),
    ]
